# Generated by Django 3.1.7 on 2021-04-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_site',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='تحصیلات'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='gitgub_address',
            field=models.URLField(default='www.example-gitgub-address.com'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='insta_address',
            field=models.URLField(default='www.example-instagram-address.com'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='tel_address',
            field=models.URLField(default='www.example-telegram-address.com'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='about_us',
            field=models.TextField(blank=True, default='ASL', null=True, verbose_name='درباره من'),
        ),
    ]
