# Generated by Django 3.1.7 on 2021-04-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0002_auto_20210426_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='about_site',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='درباره سایت '),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.URLField(max_length=50, verbose_name='ایمیل'),
        ),
    ]
