# Generated by Django 3.1.7 on 2021-04-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0003_auto_20210426_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='about_site',
            field=models.TextField(blank=True, max_length=465, null=True, verbose_name='درباره سایت '),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='about_us',
            field=models.TextField(blank=True, default='ASL', max_length=465, null=True, verbose_name='درباره من'),
        ),
    ]
