# Generated by Django 3.1.7 on 2021-04-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0004_auto_20210426_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='ایمیل'),
        ),
    ]
