# Generated by Django 3.1.7 on 2021-04-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='full_name',
            field=models.CharField(max_length=10, verbose_name='نام و نام خانوادگی'),
        ),
    ]
