# Generated by Django 3.1.7 on 2021-03-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210328_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
