# Generated by Django 3.1.7 on 2021-04-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210404_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['status', 'created_on']},
        ),
    ]
