# Generated by Django 3.1.7 on 2021-04-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hits',
        ),
    ]
