# Generated by Django 3.1.7 on 2021-04-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210413_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['status', '-created_on']},
        ),
    ]
