# Generated by Django 3.1.7 on 2021-04-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carddetail',
            old_name='order',
            new_name='cart',
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='count',
            field=models.IntegerField(default=1, verbose_name='تعداد'),
        ),
    ]
