# Generated by Django 3.1.7 on 2021-04-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210419_1854'),
        ('cart', '0002_auto_20210418_1742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardDetail',
            new_name='CartDetail',
        ),
    ]
